### ISSUE TITLE
must supply at least one object to concatenate

### ISSUE THREAD

**Issue by JieWang21** [Sydney-Informatics-Hub/geodata-harvester#14] opened 2023-08-22 11:55 UTC
Hi Seb, just tried this new version of geodata-harvester. It works when downloading gee stuff. However, when downloading DEA and DEM, it always fails and complains "ValueError: must supply at least one object to concatenate". Any suggestions? Thanks!

**Comment by sebhaan** [comment] 2023-08-23 00:18
To reproduce the error can you provide more details about your settings by attaching the settings file. Please check that your version is updated to the latest version v1.1.1 and try to run example_harvest.ipynb with the default 'settings_harvest.yaml' file, which should pass the test.

**Comment by sebhaan** [comment] 2023-08-23 02:23
Resolved via email communication. Issue was due to exceeding data size download limits and timeouts on data provider servers. Suggested solution: decrease download size by selecting smaller area or coarser resolution, or split up requested download region in seperate tiles.

**Closed by sebhaan** 2023-08-23 02:23 UTC
